name: Hello World

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          sudo sh -c "apt-get update && apt-get install -y make curl"
      - name: install JDK
        run: |
          sudo mkdir -p /usr/java
          cd /usr/java
          sudo sh -c "curl -fL https://download.bell-sw.com/java/17.0.13+12/bellsoft-jdk17.0.13+12-linux-amd64.tar.gz | tar xz"
          sudo ln -sf jdk-17.0.13 latest
          echo "JAVA_HOME=/usr/java/latest" >> "$GITHUB_ENV"
          echo "/usr/java/latest/bin" >> "$GITHUB_PATH"
      - name: install maven
        run: |
          sudo mkdir -p /usr/maven
          cd /usr/maven
          sudo sh -c "curl -fL https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xz"
          sudo ln -sf apache-maven-3.9.9 latest
          echo "/usr/maven/latest/bin" >> "$GITHUB_PATH"
      - name: build
        run: make docker
