name: Hello World

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get update
          apt-get install -y make curl
      - run: make
